package xyz.xenondevs.origami;

import org.jspecify.annotations.Nullable;
import org.objectweb.asm.ClassWriter;
import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import java.lang.invoke.MethodHandles;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Manages {@link MethodHandles.Lookup} of plugins.
 */
public final class LookupProxy {
    
    private static final String LOOKUP_PREFIX = "Origami$LookupProxy";
    private static final Map<String, MethodHandles.Lookup> PLUGIN_LOOKUPS = new ConcurrentHashMap<>();
    
    private LookupProxy() {
    }
    
    /**
     * Stores name and bytecode of a lookup class,
     * which is a simple class with just one method that return the value of {@link MethodHandles#lookup()}.
     *
     * @param name     The name of the lookup class.
     * @param bytecode The bytecode of the lookup class.
     * @see #createLookupClass(String)
     */
    public record LookupClassDefinition(String name, byte[] bytecode) {
    }
    
    /**
     * Retrieves a {@link MethodHandles.Lookup} with full privileges for the Minecraft server.
     *
     * @return The {@link MethodHandles.Lookup} for the Minecraft server.
     */
    @SuppressWarnings("unused") // called reflectively from OrigamiJit
    public static MethodHandles.Lookup getLookupForMinecraft() {
        return MethodHandles.lookup();
    }
    
    /**
     * Retrieves a {@link MethodHandles.Lookup} with full privileges for the given plugin.
     * This requires prior initialization by defining the class from {@link #createLookupClass(String)}
     * inside the plugin's class loader and initializing it via {@link #initPluginLookup(String, Class)}.
     *
     * @param pluginName The name of the plugin for which to retrieve a lookup.
     *                   Can be {@code null} to retrieve a lookup for the Minecraft server.
     * @return The {@link MethodHandles.Lookup} for the specified plugin.
     */
    public static MethodHandles.Lookup getLookupFor(@Nullable String pluginName) {
        if (pluginName == null)
            return MethodHandles.lookup();
        
        var lookup = PLUGIN_LOOKUPS.get(pluginName);
        if (lookup == null) {
            throw new IllegalStateException("Lookup for plugin '" + pluginName + "' is not initialized.");
        }
        return lookup;
    }
    
    /**
     * Retrieves a private access {@link MethodHandles.Lookup} for the given plugin and target class.
     * This requires prior initialization by defining the class from {@link #createLookupClass(String)}
     * inside the plugin's class loader and initializing it via {@link #initPluginLookup(String, Class)}.
     *
     * @param pluginName  The name of the plugin for which to retrieve a lookup.
     *                    Can be {@code null} to retrieve a lookup for the Minecraft server.
     * @param targetClass The target class
     * @return A {@link MethodHandles.Lookup} for the target class, with private access.
     * @throws IllegalAccessException if targetClass is a primitive type or void or array class
     */
    public static MethodHandles.Lookup getPrivateLookupFor(@Nullable String pluginName, Class<?> targetClass) throws IllegalAccessException {
        return MethodHandles.privateLookupIn(targetClass, getLookupFor(pluginName));
    }
    
    /**
     * Retrieves the {@link ClassLoader} of the given plugin.
     * This requires prior initialization by defining the class from {@link #createLookupClass(String)}
     * inside the plugin's class loader and initializing it via {@link #initPluginLookup(String, Class)}.
     *
     * @param pluginName The name of the plugin whose class loader to retrieve.
     *                   Can be {@code null} for the Minecraft server.
     * @return The {@link ClassLoader} of the specified plugin.
     */
    public static ClassLoader getLoaderFor(@Nullable String pluginName) {
        return getLookupFor(pluginName).lookupClass().getClassLoader();
    }
    
    /**
     * Uses the given lookup class (which was previously generated by {@link #createLookupClass(String)})
     * to retrieve the plugin's {@link MethodHandles.Lookup} and make it accessible via {@link #getLookupFor(String)} ()}.
     *
     * @param pluginName  The name of the plugin where the lookup class was defined.
     * @param lookupClass The lookup class that is defined inside the plugin's class loader.
     */
    @SuppressWarnings("unused") // called from (patched) PaperPluginClassLoader
    public static void initPluginLookup(String pluginName, Class<?> lookupClass) {
        MethodHandles.Lookup lookup;
        try {
            lookup = (MethodHandles.Lookup) lookupClass.getMethod("getLookup").invoke(null);
        } catch (ReflectiveOperationException e) {
            throw new IllegalStateException("Failed to retrieve lookup from " + lookupClass.getName(), e);
        }
        
        if (PLUGIN_LOOKUPS.putIfAbsent(pluginName, lookup) != null) {
            throw new IllegalStateException("Lookup for plugin '" + pluginName + "' is already initialized.");
        }
    }
    
    /**
     * Generates the name and bytecode for a "lookup class", which is a simple class with just one method
     * that return the value of {@link MethodHandles#lookup()}.
     * <p>
     * The class is intended to be defined inside the class loader of a plugin and can then be used
     * to obtain a {@link MethodHandles.Lookup} for the given plugin in {@link #initPluginLookup(String, Class)}.
     *
     * @param pluginName The name of the plugin for which this lookup class is for.
     *                   This will influence the returned lookup class name.
     * @return The definition for the lookup class, consisting of its name and bytecode.
     */
    @SuppressWarnings("unused") // called from (patched) PaperPluginClassLoader
    public static LookupClassDefinition createLookupClass(String pluginName) {
        // random name following the pattern Origami$LookupProxy$MyPlugin$1234
        var className = LOOKUP_PREFIX +
                        "$" + pluginName.chars()
                            .filter(Character::isJavaIdentifierPart)
                            .collect(
                                StringBuilder::new,
                                StringBuilder::appendCodePoint,
                                StringBuilder::append
                            ).toString()
                        + "$"
                        + System.currentTimeMillis();
        
        var writer = new ClassWriter(ClassWriter.COMPUTE_MAXS);
        writer.visit(
            Opcodes.V21,
            Opcodes.ACC_PUBLIC | Opcodes.ACC_FINAL,
            className,
            null,
            "java/lang/Object",
            null
        );
        
        MethodVisitor method = writer.visitMethod(
            Opcodes.ACC_PUBLIC | Opcodes.ACC_STATIC,
            "getLookup",
            "()Ljava/lang/invoke/MethodHandles$Lookup;",
            null,
            null
        );
        method.visitCode();
        method.visitMethodInsn(
            Opcodes.INVOKESTATIC,
            "java/lang/invoke/MethodHandles",
            "lookup",
            "()Ljava/lang/invoke/MethodHandles$Lookup;",
            false
        );
        method.visitInsn(Opcodes.ARETURN);
        method.visitMaxs(0, 0);
        method.visitEnd();
        writer.visitEnd();
        
        return new LookupClassDefinition(className, writer.toByteArray());
    }
    
}
