[metadata]
format.version = "1.1"

[versions]
asm = "9.10.1"
kotlin = "2.4.10"
mixin = "0.17.3+mixin.0.8.7"
mixinextras = "0.5.4"
jspecify = "1.0.0"
joptsimple = "5.0.4"
slf4j = "2.0.17"
commons = "1.37"

[libraries]
accesswidener = { group = "net.fabricmc", name = "access-widener", version = "2.1.0" }
asm = { group = "org.ow2.asm", name = "asm", version.ref = "asm" }
asm-tree = { group = "org.ow2.asm", name = "asm-tree", version.ref = "asm" }
diffpatch = { group = "io.codechicken", name = "DiffPatch", version = "2.1.0.43" }
javaparser = { group = "com.github.javaparser", name = "javaparser-symbol-solver-core", version = "3.28.2" }
jspecify = { group = "org.jspecify", name = "jspecify", version.ref = "jspecify" }
joptsimple = { group = "net.sf.jopt-simple", name = "jopt-simple", version.ref = "joptsimple" }
kotlin-plugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
gson = { group = "com.google.code.gson", name = "gson", version = "2.13.2" }
mixin = { group = "net.fabricmc", name = "sponge-mixin", version.ref = "mixin" }
mixinextras = { group = "io.github.llamalad7", name = "mixinextras-common", version.ref = "mixinextras" }
slf4j = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
snakeyaml = { group = "org.snakeyaml", name = "snakeyaml-engine", version = "3.0.1" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version = "1.6.1" }
commons-gson = { group = "xyz.xenondevs.commons", name = "commons-gson", version.ref = "commons" }

[bundles]
asm = ["asm", "asm-tree"]
