package xyz.xenondevs.origami.task.run

import org.gradle.api.file.ConfigurableFileCollection
import org.gradle.api.file.ProjectLayout
import org.gradle.api.file.RegularFileProperty
import org.gradle.api.tasks.InputFile
import org.gradle.api.tasks.Internal
import org.gradle.api.tasks.JavaExec
import org.gradle.api.tasks.Optional
import org.gradle.api.tasks.PathSensitive
import org.gradle.api.tasks.PathSensitivity
import java.net.URI
import java.nio.file.Path
import java.nio.file.attribute.FileTime
import java.util.jar.Attributes
import java.util.jar.JarOutputStream
import java.util.jar.Manifest
import javax.inject.Inject
import kotlin.io.path.absolutePathString
import kotlin.io.path.createDirectories
import kotlin.io.path.exists
import kotlin.io.path.isDirectory
import kotlin.io.path.outputStream
import kotlin.io.path.setLastModifiedTime

internal abstract class RunServer : JavaExec() {
    
    @get:Internal
    var useAotCache = true
    
    @get:Internal
    abstract val plugins: ConfigurableFileCollection
    
    @get:InputFile
    @get:Optional
    @get:PathSensitive(PathSensitivity.NONE)
    abstract val aotCacheFingerprint: RegularFileProperty
    
    @get:Inject
    abstract val projectLayout: ProjectLayout
    
    override fun exec() {
        val cacheDir = projectLayout.buildDirectory.dir("origami/").get().asFile.toPath()
        workingDir.mkdirs()
        cacheDir.createDirectories()
        
        for (plugin in plugins.files) {
            args("--add-plugin", plugin.absolutePath)
        }
        
        if (useAotCache) {
            val fingerprint = aotCacheFingerprint.get().asFile.readText().trim()
            val aotCacheFile = cacheDir.resolve("server-$fingerprint.aot")
            val classpathJar = generateRelativeClasspathJar(cacheDir)
            setClasspath(projectLayout.files(classpathJar.toFile()))
            
            jvmArgs("-XX:+UnlockDiagnosticVMOptions")
            jvmArgs("-Dorigami.aot.cache=${aotCacheFile.absolutePathString()}")
            
            if (aotCacheFile.exists()) {
                logger.lifecycle("Using existing AOT cache")
                jvmArgs(
                    "-XX:AOTMode=on",
                    "-XX:AOTCache=${aotCacheFile.absolutePathString()}"
                )
            } else {
                logger.lifecycle("Recording AOT cache")
                jvmArgs(
                    "-XX:AOTMode=record",
                    "-XX:AOTConfiguration=${aotCacheFile.absolutePathString()}.config"
                )
            }
        }
        
        super.exec()
    }
    
    // workaround due to a bug in the JDK not properly parsing the URL style file:/... for AOT cache
    // (this style is generated by Gradle into the "javaexec-classpath" files when the classpath is too long to fit on the windows command line)
    // related issue: https://bugs.openjdk.org/browse/JDK-8373028 
    private fun generateRelativeClasspathJar(directory: Path): Path {
        val classpathJar = directory.resolve("relative-classpath.jar")
            .toAbsolutePath()
            .normalize()
        
        val base = classpathJar.parent
        val entries = classpath.files.map { file ->
            val path = file.toPath()
                .toAbsolutePath()
                .normalize()
            val relative = base.relativize(path)
                .toString()
                .replace('\\', '/')
            var uri = URI(null, null, relative, null).toASCIIString()
            if (path.isDirectory() && !uri.endsWith('/'))
                uri += "/"
            uri
        }
        
        JarOutputStream(
            classpathJar.outputStream(),
            Manifest().apply {
                mainAttributes[Attributes.Name.MANIFEST_VERSION] = "1.0"
                mainAttributes[Attributes.Name.CLASS_PATH] = entries.joinToString(" ")
            }
        ).close()
        
        classpathJar.setLastModifiedTime(FileTime.fromMillis(0L))
        return classpathJar
    }
    
}
